[2024-10-21T05:52:22.593+0000] {processor.py:161} INFO - Started process (PID=115) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:52:22.593+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T05:52:22.595+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:52:22.594+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:52:22.601+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:52:22.599+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:52:22.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:52:22.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.027 seconds
[2024-10-21T05:52:52.774+0000] {processor.py:161} INFO - Started process (PID=125) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:52:52.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T05:52:52.776+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:52:52.776+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:52:52.780+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:52:52.778+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:52:52.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:52:52.798+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.029 seconds
[2024-10-21T05:53:22.999+0000] {processor.py:161} INFO - Started process (PID=135) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:53:22.999+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T05:53:23.000+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:53:23.000+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:53:23.004+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:53:23.002+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:53:23.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:53:23.019+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.024 seconds
[2024-10-21T05:53:53.205+0000] {processor.py:161} INFO - Started process (PID=145) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:53:53.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T05:53:53.208+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:53:53.207+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:53:53.211+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:53:53.209+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:53:53.212+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:53:53.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.024 seconds
[2024-10-21T05:54:23.376+0000] {processor.py:161} INFO - Started process (PID=161) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:54:23.376+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T05:54:23.377+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:54:23.377+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:54:23.380+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:54:23.379+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:54:23.381+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:54:23.395+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.024 seconds
[2024-10-21T05:54:53.584+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:54:53.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T05:54:53.586+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:54:53.586+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:54:53.589+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:54:53.587+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:54:53.589+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:54:53.604+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.024 seconds
[2024-10-21T05:55:23.789+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:55:23.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T05:55:23.791+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:55:23.791+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:55:23.794+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:55:23.792+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:55:23.795+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:55:23.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.025 seconds
[2024-10-21T05:55:53.964+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:55:53.965+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T05:55:53.966+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:55:53.966+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:55:53.970+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:55:53.968+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:55:53.971+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:55:53.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.025 seconds
[2024-10-21T05:56:24.189+0000] {processor.py:161} INFO - Started process (PID=200) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:56:24.189+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T05:56:24.191+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:56:24.190+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:56:24.195+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:56:24.193+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:56:24.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:56:24.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.030 seconds
[2024-10-21T05:56:54.407+0000] {processor.py:161} INFO - Started process (PID=210) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:56:54.408+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T05:56:54.410+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:56:54.410+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:56:54.414+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:56:54.412+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:56:54.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:56:54.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.029 seconds
[2024-10-21T05:57:24.576+0000] {processor.py:161} INFO - Started process (PID=220) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:57:24.576+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T05:57:24.578+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:57:24.577+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:57:24.580+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:57:24.579+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:57:24.581+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:57:24.595+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.023 seconds
[2024-10-21T05:57:54.783+0000] {processor.py:161} INFO - Started process (PID=230) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:57:54.784+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T05:57:54.785+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:57:54.785+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:57:54.788+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:57:54.786+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:57:54.789+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:57:54.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.025 seconds
[2024-10-21T05:58:24.993+0000] {processor.py:161} INFO - Started process (PID=240) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:58:24.994+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T05:58:24.995+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:58:24.995+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:58:24.999+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:58:24.997+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:58:25.001+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:58:25.015+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.026 seconds
[2024-10-21T05:58:55.152+0000] {processor.py:161} INFO - Started process (PID=250) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:58:55.153+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T05:58:55.155+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:58:55.154+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:58:55.158+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:58:55.156+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:58:55.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:58:55.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.025 seconds
[2024-10-21T05:59:25.375+0000] {processor.py:161} INFO - Started process (PID=260) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:59:25.376+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T05:59:25.377+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:59:25.377+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:59:25.380+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:59:25.379+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:59:25.381+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:59:25.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.028 seconds
[2024-10-21T05:59:55.589+0000] {processor.py:161} INFO - Started process (PID=270) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:59:55.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T05:59:55.591+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:59:55.591+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:59:55.594+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:59:55.593+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:59:55.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T05:59:55.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.024 seconds
[2024-10-21T06:00:25.751+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:00:25.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T06:00:25.753+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:00:25.753+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:00:25.756+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:00:25.755+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:00:25.757+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:00:25.774+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.027 seconds
[2024-10-21T06:00:55.971+0000] {processor.py:161} INFO - Started process (PID=290) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:00:55.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T06:00:55.973+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:00:55.973+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:00:55.977+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:00:55.975+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:00:55.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:00:55.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.026 seconds
[2024-10-21T06:01:26.170+0000] {processor.py:161} INFO - Started process (PID=300) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:01:26.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T06:01:26.172+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:01:26.172+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:01:26.175+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:01:26.173+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:01:26.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:01:26.189+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.023 seconds
[2024-10-21T06:01:56.329+0000] {processor.py:161} INFO - Started process (PID=310) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:01:56.330+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T06:01:56.331+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:01:56.331+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:01:56.334+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:01:56.333+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:01:56.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:01:56.348+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.023 seconds
[2024-10-21T06:02:26.556+0000] {processor.py:161} INFO - Started process (PID=320) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:02:26.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T06:02:26.558+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:02:26.558+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:02:26.561+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:02:26.559+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:02:26.562+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:02:26.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.023 seconds
[2024-10-21T06:02:56.771+0000] {processor.py:161} INFO - Started process (PID=330) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:02:56.772+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T06:02:56.773+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:02:56.773+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:02:56.777+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:02:56.775+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:02:56.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:02:56.793+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.027 seconds
[2024-10-21T06:03:26.931+0000] {processor.py:161} INFO - Started process (PID=340) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:03:26.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T06:03:26.933+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:03:26.932+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:03:26.936+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:03:26.934+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:03:26.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:03:26.951+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.024 seconds
[2024-10-21T06:03:57.150+0000] {processor.py:161} INFO - Started process (PID=350) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:03:57.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T06:03:57.153+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:03:57.152+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:03:57.155+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:03:57.154+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:03:57.156+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:03:57.169+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.022 seconds
[2024-10-21T06:04:27.349+0000] {processor.py:161} INFO - Started process (PID=360) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:04:27.350+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T06:04:27.351+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:04:27.351+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:04:27.354+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:04:27.353+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:04:27.355+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:04:27.369+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.024 seconds
[2024-10-21T06:04:57.515+0000] {processor.py:161} INFO - Started process (PID=370) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:04:57.517+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T06:04:57.518+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:04:57.518+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:04:57.522+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:04:57.520+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:04:57.523+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:04:57.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.025 seconds
[2024-10-21T06:05:27.730+0000] {processor.py:161} INFO - Started process (PID=380) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:05:27.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T06:05:27.732+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:05:27.732+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:05:27.735+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:05:27.734+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:05:27.736+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:05:27.750+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.023 seconds
[2024-10-21T06:05:57.924+0000] {processor.py:161} INFO - Started process (PID=390) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:05:57.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T06:05:57.927+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:05:57.927+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:05:57.931+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:05:57.929+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:05:57.932+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:05:57.947+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.028 seconds
[2024-10-21T06:06:28.084+0000] {processor.py:161} INFO - Started process (PID=400) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:06:28.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T06:06:28.086+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:06:28.085+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:06:28.089+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:06:28.087+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:06:28.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:06:28.102+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.022 seconds
[2024-10-21T06:06:58.312+0000] {processor.py:161} INFO - Started process (PID=410) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:06:58.314+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T06:06:58.316+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:06:58.315+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:06:58.320+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:06:58.318+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:06:58.321+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:06:58.340+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.034 seconds
[2024-10-21T06:07:28.564+0000] {processor.py:161} INFO - Started process (PID=420) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:07:28.565+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T06:07:28.566+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:07:28.566+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:07:28.569+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:07:28.568+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:07:28.571+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:07:28.584+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.024 seconds
[2024-10-21T06:07:58.727+0000] {processor.py:161} INFO - Started process (PID=430) to work on /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:07:58.729+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py for tasks to queue
[2024-10-21T06:07:58.730+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:07:58.729+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:07:58.733+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:07:58.731+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:07:58.734+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py
[2024-10-21T06:07:58.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/.ipynb_checkpoints/jupyter_test-checkpoint.py took 0.025 seconds
