[2024-10-21T05:52:22.586+0000] {processor.py:161} INFO - Started process (PID=114) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:52:22.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T05:52:22.588+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:52:22.588+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:52:22.592+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:52:22.591+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:52:22.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:52:22.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.026 seconds
[2024-10-21T05:52:52.765+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:52:52.766+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T05:52:52.768+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:52:52.767+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:52:52.771+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:52:52.770+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:52:52.772+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:52:52.786+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.026 seconds
[2024-10-21T05:53:22.993+0000] {processor.py:161} INFO - Started process (PID=134) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:53:22.993+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T05:53:22.994+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:53:22.994+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:53:22.997+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:53:22.996+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:53:22.998+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:53:23.013+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.024 seconds
[2024-10-21T05:53:53.199+0000] {processor.py:161} INFO - Started process (PID=144) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:53:53.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T05:53:53.201+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:53:53.201+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:53:53.204+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:53:53.203+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:53:53.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:53:53.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.025 seconds
[2024-10-21T05:54:23.370+0000] {processor.py:161} INFO - Started process (PID=160) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:54:23.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T05:54:23.372+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:54:23.372+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:54:23.375+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:54:23.373+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:54:23.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:54:23.389+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.023 seconds
[2024-10-21T05:54:53.578+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:54:53.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T05:54:53.580+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:54:53.580+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:54:53.582+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:54:53.581+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:54:53.583+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:54:53.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.024 seconds
[2024-10-21T05:55:23.783+0000] {processor.py:161} INFO - Started process (PID=180) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:55:23.784+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T05:55:23.785+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:55:23.785+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:55:23.788+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:55:23.786+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:55:23.788+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:55:23.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.025 seconds
[2024-10-21T05:55:53.958+0000] {processor.py:161} INFO - Started process (PID=190) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:55:53.959+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T05:55:53.960+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:55:53.960+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:55:53.963+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:55:53.962+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:55:53.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:55:53.979+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.025 seconds
[2024-10-21T05:56:24.180+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:56:24.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T05:56:24.182+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:56:24.181+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:56:24.184+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:56:24.183+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:56:24.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:56:24.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.024 seconds
[2024-10-21T05:56:54.398+0000] {processor.py:161} INFO - Started process (PID=209) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:56:54.400+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T05:56:54.401+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:56:54.401+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:56:54.405+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:56:54.403+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:56:54.405+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:56:54.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.026 seconds
[2024-10-21T05:57:24.570+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:57:24.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T05:57:24.572+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:57:24.571+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:57:24.574+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:57:24.573+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:57:24.575+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:57:24.590+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.024 seconds
[2024-10-21T05:57:54.777+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:57:54.777+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T05:57:54.779+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:57:54.778+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:57:54.781+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:57:54.780+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:57:54.782+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:57:54.797+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.025 seconds
[2024-10-21T05:58:24.987+0000] {processor.py:161} INFO - Started process (PID=239) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:58:24.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T05:58:24.989+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:58:24.989+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:58:24.993+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:58:24.991+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:58:24.994+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:58:25.010+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.028 seconds
[2024-10-21T05:58:55.147+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:58:55.148+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T05:58:55.149+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:58:55.149+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:58:55.152+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:58:55.150+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:58:55.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:58:55.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.025 seconds
[2024-10-21T05:59:25.366+0000] {processor.py:161} INFO - Started process (PID=259) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:59:25.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T05:59:25.368+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:59:25.368+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:59:25.371+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:59:25.370+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:59:25.373+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:59:25.390+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.029 seconds
[2024-10-21T05:59:55.578+0000] {processor.py:161} INFO - Started process (PID=269) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:59:55.579+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T05:59:55.580+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:59:55.580+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:59:55.584+0000] {logging_mixin.py:188} INFO - [2024-10-21T05:59:55.582+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T05:59:55.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T05:59:55.604+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.030 seconds
[2024-10-21T06:00:25.745+0000] {processor.py:161} INFO - Started process (PID=279) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:00:25.746+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T06:00:25.748+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:00:25.748+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:00:25.752+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:00:25.750+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:00:25.753+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:00:25.770+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.029 seconds
[2024-10-21T06:00:55.964+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:00:55.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T06:00:55.966+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:00:55.965+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:00:55.969+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:00:55.967+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:00:55.969+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:00:55.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.025 seconds
[2024-10-21T06:01:26.164+0000] {processor.py:161} INFO - Started process (PID=299) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:01:26.165+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T06:01:26.166+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:01:26.166+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:01:26.169+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:01:26.168+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:01:26.170+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:01:26.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.024 seconds
[2024-10-21T06:01:56.324+0000] {processor.py:161} INFO - Started process (PID=309) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:01:56.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T06:01:56.326+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:01:56.325+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:01:56.328+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:01:56.327+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:01:56.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:01:56.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.024 seconds
[2024-10-21T06:02:26.550+0000] {processor.py:161} INFO - Started process (PID=319) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:02:26.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T06:02:26.552+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:02:26.552+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:02:26.555+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:02:26.553+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:02:26.555+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:02:26.569+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.023 seconds
[2024-10-21T06:02:56.762+0000] {processor.py:161} INFO - Started process (PID=329) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:02:56.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T06:02:56.765+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:02:56.764+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:02:56.768+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:02:56.767+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:02:56.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:02:56.782+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.025 seconds
[2024-10-21T06:03:26.925+0000] {processor.py:161} INFO - Started process (PID=339) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:03:26.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T06:03:26.927+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:03:26.927+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:03:26.930+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:03:26.929+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:03:26.931+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:03:26.946+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.025 seconds
[2024-10-21T06:03:57.145+0000] {processor.py:161} INFO - Started process (PID=349) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:03:57.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T06:03:57.147+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:03:57.146+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:03:57.149+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:03:57.148+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:03:57.150+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:03:57.164+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.023 seconds
[2024-10-21T06:04:27.343+0000] {processor.py:161} INFO - Started process (PID=359) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:04:27.344+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T06:04:27.346+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:04:27.345+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:04:27.348+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:04:27.347+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:04:27.349+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:04:27.363+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.024 seconds
[2024-10-21T06:04:57.509+0000] {processor.py:161} INFO - Started process (PID=369) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:04:57.510+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T06:04:57.511+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:04:57.511+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:04:57.514+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:04:57.513+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:04:57.515+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:04:57.530+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.024 seconds
[2024-10-21T06:05:27.725+0000] {processor.py:161} INFO - Started process (PID=379) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:05:27.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T06:05:27.727+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:05:27.727+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:05:27.730+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:05:27.728+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:05:27.730+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:05:27.745+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.025 seconds
[2024-10-21T06:05:57.916+0000] {processor.py:161} INFO - Started process (PID=389) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:05:57.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T06:05:57.918+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:05:57.918+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:05:57.921+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:05:57.920+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:05:57.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:05:57.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.025 seconds
[2024-10-21T06:06:28.078+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:06:28.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T06:06:28.081+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:06:28.080+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:06:28.083+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:06:28.082+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:06:28.084+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:06:28.099+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.025 seconds
[2024-10-21T06:06:58.302+0000] {processor.py:161} INFO - Started process (PID=409) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:06:58.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T06:06:58.304+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:06:58.304+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:06:58.308+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:06:58.306+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:06:58.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:06:58.342+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.048 seconds
[2024-10-21T06:07:28.558+0000] {processor.py:161} INFO - Started process (PID=419) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:07:28.559+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T06:07:28.560+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:07:28.560+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:07:28.563+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:07:28.561+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:07:28.563+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:07:28.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.025 seconds
[2024-10-21T06:07:58.721+0000] {processor.py:161} INFO - Started process (PID=429) to work on /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:07:58.722+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/jupyter_test.py for tasks to queue
[2024-10-21T06:07:58.724+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:07:58.723+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:07:58.726+0000] {logging_mixin.py:188} INFO - [2024-10-21T06:07:58.725+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/jupyter_test.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/jupyter_test.py", line 486, in <module>
    "execution_count": null,
                       ^^^^
NameError: name 'null' is not defined
[2024-10-21T06:07:58.727+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/jupyter_test.py
[2024-10-21T06:07:58.742+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/jupyter_test.py took 0.024 seconds
